name: README links

on:
  pull_request:
  push:

jobs:
  check-readme-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python scripts/update_readme_links.py --check || (echo "::error file=README.md::README links out of date. Run 'python scripts/update_readme_links.py'." && exit 1)
